markdown: rdiscount
permalink: /:year/:month/:day/:title/
author: Zoey
url: http://www.daijiang.name/zoey
highlighter: pygments

title: Zoey
subTitle: A blog of my life.
description: This blog is a diary of my life.

paginate: 8
safe: false
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /zoey/index.html
  - text: 文章归档
    url: /zoey/archives.html
  - text: 分类
    url: /zoey/categories.html
  - text: 标签
    url: /zoey/tags.html
  - text: 关于
    url: /zoey/about.html
  - text: 留言
    url: /zoey/guestbook.html
  - text: 链接
    url: /zoey/links.html
  - text: 订阅
    url: /zoey/feed.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: 
  - class: fa-facebook
    url:
  - class: fa-github
    url: http://github.com/daijiang
  - class: fa-weibo
    url:
  - class: fa-renren
    url:
  - class: fa-twitter
    url: http://twitter.com/_djli
  - class: fa-rss
    url: http://www.daijiang.name/zoey/feed.html


#评论信息
disqus:
  config: true
  id: zoeysblog
